image: registry.git.fh-aachen.de/tb3838s/jdeserialize/ant-builder

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-jar:
  stage: build
  tags:
    - shared
  script:
    - cd jdeserialize
    - ant compile
    - ant build-jar # seperated for better failure logs

javadoc:
  stage: build
  tags:
    - shared
  script:
    - cd jdeserialize
    - ant javadoc

deploy-job:
  stage: deploy
  tags:
    - shared
  script:
    - echo "Deploying jdeserialize..."
    - mkdir artifacts/{javadoc,testcases}
    - cp jdeserialize/jdeserialize.jar artifacts/
    - cp -r jdeserialize/javadoc/ artifacts/javadoc/
    - cp jdeserialize/ORIGINAL-LICENSE.md artifacts/ORIGINAL-LICENSE.md
    - cp jdeserialize/testcases artifacts/testcases/
