image: registry.git.fh-aachen.de/tb3838s/jdeserialize/ant-builder

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-jar:
  stage: build
  tags:
    - shared
  script:
    - cd jdeserialize
    - ant compile
    - ant build-jar # seperated for better failure logs
  artifacts:
    paths:
      - jdeserialize/jdeserialize.jar

javadoc:
  stage: build
  tags:
    - shared
  script:
    - cd jdeserialize
    - ant javadoc
  artifacts:
    paths:
      - jdeserialize/javadoc

deploy-job:
  stage: deploy
  tags:
    - shared
  script:
    - echo "Deploying jdeserialize..."
    - mkdir -p artifacts/{javadoc,testcases}
    - cp jdeserialize/jdeserialize.jar artifacts/
    - cp -r jdeserialize/javadoc/ artifacts/
    - cp jdeserialize/ORIGINAL-LICENSE.md artifacts/ORIGINAL-LICENSE.md
    - cp -r jdeserialize/testcases artifacts/
  artifacts:
    name: "jdeserializeFull"
    paths:
      - artifacts/*
    
